[theme]
# Primary color for interactive elements
primaryColor = "#FF6B6B"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar
secondaryBackgroundColor = "#F5F5F5"

# Color used for almost all text
textColor = "#262730"

# Font family for all text
font = "sans serif"

[server]
# Port configuration (optional, Streamlit Cloud handles this)
headless = true
port = 8501

[browser]
# Gather usage stats (optional)
gatherUsageStats = false

[client]
# Show error details in the browser
showErrorDetails = true